# based on https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true

# console_title_template = "{{ .Shell }} in {{ .Folder }}"
# 
[[blocks]] # prompt
type = "prompt"
alignment = "left"
# newline = true

[[blocks.segments]] # Path
type = "path"
style = "plain"
background = "transparent"
foreground = "cyan"
template = "{{ .Path }}"

[blocks.segments.properties]
style = "full"

[[blocks.segments]] # Git
type = "git"
style = "plain"
foreground = "lightGreen"
background = "transparent"
template = " ({{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}) "

[blocks.segments.properties]
branch_icon = " "
fetch_stash_count = true
fetch_status = true
fetch_upstream_icon = true
fetch_worktree_count = true

[[blocks]] # rprompt
type = "prompt"
alignment = "right"

[[blocks.segments]] # Python
type = "python"
style = "plain"
foreground = "yellow"
background = "transparent"
template = "( {{ .Venv }} v{{ .Full }}) "

[blocks.segments.properties]
home_enabled = true

[[blocks.segments]] # Execution Time
type = "executiontime"
style = "plain"
foreground = "lightRed"
background = "transparent"
template = "  {{ .FormattedMs }} "

[blocks.segments.properties]
threshold = 0

[[blocks]] # prompt
type = "prompt"
alignment = "left"

[[blocks.segments]]
type = "text"
style = "plain"
foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}magenta{{end}}",
]
background = "transparent"
template = "❯"

[transient_prompt]
foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}magenta{{end}}",
]
background = "transparent"
template = "❯ "

[secondary_prompt]
foreground = "magenta"
background = "transparent"
template = "❯❯ "
